# Generated by Django 4.0.3 on 2022-03-07 13:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_description',
            field=models.TextField(help_text='короткое описание для превью публикации', max_length=500, verbose_name='Превью описание'),
        ),
    ]
