# Generated by Django 4.0.3 on 2022-03-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='user_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
